### PR TITLE
Added HMD position documentation

### PR DESCRIPTION
**Pull request by mwmwmw**
- Where to find the HMD position
- Parenting the VR camera and controllers to an object.

### CODE REVIEW

**Comment by sniok** [comment]
nice, thanks!

**Comment by sniok** [comment]
Is this bundling of controllers and hmd under one mesh is related to locomotion? Having reusable locomotion in react-xr would be great

**Comment by mwmwmw** [comment]
Sorry for the delayed reply. 

Yes, I' have some basic locomotion components I will add to react-xr when I have chance to finish. 

The goal is to have a set of components the developer can piece together to create different locomotion strategies.

I see parenting the camera and controllers to an object to be the simplest way to move the player around. It makes it easy to parent the viewer object to a parent object (like a vehicle).

**Comment by checksummaster** [comment]
Parenting xr camera using "gl.xr.isPresenting ? gl.xr.getCamera(camera) : camera;" seem not work .  I think that the camera absolute position is always overwrite by the HUD position?

This is a small code to make some basic locomotion with keyboard. (far from perfect)

`
import React , { useRef,useEffect} from 'react'
import { useThree  } from 'react-three-fiber'
import { useXR   } from 'react-xr'

export default function Locomotion({position})
{
    const mesh = useRef()
    var speedposition = 0.05;
    var speedrotation = Math.PI/180;

    const { gl, camera } = useThree()

    useEffect(() => {
        const cam = camera; //gl.xr.isPresenting ? gl.xr.getCamera(camera) : camera;
        mesh.current.position.set(position[0],position[1],position[2]);

        cam.position.set(0,0,0);
        mesh.current.add(cam); 
        console.log(`Add cam ${gl.xr.isPresenting?"xr":"normal"}`)
        return () => mesh.current.remove(cam)
    }, [gl.xr.isPresenting, gl.xr, camera, mesh])


    const { controllers } = useXR()
        useEffect(() => {
            console.log(controllers);
        if (controllers.length > 0) controllers.forEach((c) => mesh.current.add(c.grip))
        return () => controllers.forEach((c) => mesh.current.remove(c.grip))
    }, [controllers, mesh])


    document.onkeydown = (e)=>{

        const cam =  gl.xr.isPresenting ? gl.xr.getCamera(camera) : camera;

        const body = mesh.current;

        console.log(body.position.x,body.position.y,body.position.z)

        var speedforward = Math.cos(body.rotation.y) * speedposition;
        var speedlateral = Math.sin(body.rotation.y) * speedposition;
        
        if (e.key === "ArrowUp" || e.key === "w") {
            body.translateZ (-speedforward);
            body.translateX (-speedlateral);
        }
        else if (e.key === "ArrowDown" || e.key === "s") {
            body.translateZ (speedforward);
            body.translateX (speedlateral);
        }
        else if (e.key === "ArrowLeft" || e.key === "a") {
            body.translateZ (speedlateral);
            body.translateX (-speedforward);
        }
        else if (e.key === "ArrowRight" || e.key === "d") {
            body.translateZ (-speedlateral);
            body.translateX (speedforward);
        }
        else if (e.key === 'q') {
            body.rotation.y += speedrotation;
        }
        else if (e.key === 'e') {
            body.rotation.y -= speedrotation;
        }
    }
    
    return (
        <mesh ref={mesh} position={position} scale={[0.1,0.1,0.1]}>
            <boxBufferGeometry attach="geometry" />
            <meshStandardMaterial attach="material" color="#00ff00" />
        </mesh>
    );
}`

**Pull request merged**
